@startuml
start
!include theme.puml


while (tourne ?) is (oui)

  :Mettre à jour bots;
  note right
    updateTraces()
    update(dt)
  end note



  if (Jeu commencé ?) then (non)

    if (temps écoulé ?) then (oui)
      :Démarrer partie;
    else (non)
      :Diffusion du chronos;
    endif

  else (oui)

    if (fin de partie ?) then (oui)
      stop
    endif

  endif

  if (Jeu commencé ?) then (oui)
    :Mise a jour des mouvements joueurs;
    :Diffusion des états;
  endif

  :Pause (tick);

endwhile (non)

stop
@enduml