@startuml
!include theme.puml


participant Client
participant Serveur


== Salon ==
Client -> Serveur : Changer statut/rôle/params
activate Serveur
Serveur -> Serveur : Vérifier changement
Serveur --> Client : paramètres, liste joueurs
deactivate Serveur
opt Tous le monde prêt
alt rôles valides
Serveur --> Client : début de partie
Client -> Client : changer scène (jeu)
activate Client
deactivate Client
else erreur
Serveur --> Client : erreur
end
end
== Jeu ==
Client -> Serveur : demander déplacement
activate Serveur
Serveur -> Serveur : traiter déplacement
Serveur --> Client : état du jeu
deactivate Serveur
opt Jeu fini
Serveur --> Client : fin de jeu
Client -> Client : changer scène (fin de jeu)
end
@enduml