' =========================
' RESET & BASE
' =========================
!theme plain
!pragma layout smetana

skinparam backgroundColor #FFFFFF
skinparam dpi 150
skinparam shadowing false
skinparam roundcorner 10

' =========================
' FONT
' =========================
skinparam defaultFontName Arial
skinparam defaultFontSize 14
skinparam defaultFontColor #222222

' =========================
' COULEURS PRINCIPALES
' =========================
!define MAIN #1F4E79
!define GRAY #6C7A89
!define LIGHT_BLUE #dceeff
!define LIGHT #EEF3F8

' =========================
' TITRES
' =========================
skinparam titleFontSize 18
skinparam titleFontColor MAIN

' =========================
' FLÈCHES (GLOBAL)
' =========================
skinparam ArrowColor MAIN
skinparam ArrowThickness 1.5

' =========================
' CLASSES
' =========================
skinparam classAttributeIconSize 0

skinparam class {
    BackgroundColor #F9FBFD
    BorderColor MAIN
    FontColor #222222

    AttributeFontColor #444444
    MethodFontColor #444444

    FontSize 14
    AttributeFontSize 13
    MethodFontSize 13

    BorderThickness 1.5
    DividerColor #D0D7E2
}
skinparam classAttributeIconSize 0
hide circle
skinparam linetype ortho
skinparam class {
    HeaderBackgroundColor LIGHT_BLUE
}
skinparam ArrowColor MAIN
skinparam ArrowThickness 1.5
skinparam ArrowFontColor #333333



' =========================
' SEQUENCE DIAGRAM
' =========================
skinparam sequence {
    ArrowColor MAIN
    LifeLineBorderColor MAIN
    LifeLineBackgroundColor LIGHT_BLUE
    ParticipantBorderColor MAIN
    ParticipantBackgroundColor LIGHT_BLUE
    ParticipantFontColor #222222
    ActorBorderColor MAIN
    ActorBackgroundColor LIGHT_BLUE
}
' =========================
' COMPONENT / RECTANGLE
' =========================
skinparam component {
    BackgroundColor #FFFFFF
    BorderColor MAIN
}

skinparam rectangle {
    BackgroundColor #FFFFFF
    BorderColor MAIN
}

' =========================
' NODE / DATABASE
' =========================
skinparam node {
    BackgroundColor #FFFFFF
    BorderColor MAIN
}

skinparam database {
    BackgroundColor #FFFFFF
    BorderColor MAIN
}

' =========================
' NOTES
' =========================
skinparam note {
    BackgroundColor LIGHT
    BorderColor GRAY
    FontColor #222222
}

' =========================
' PACKAGES
' =========================
skinparam package {
    BorderColor MAIN
    BackgroundColor #F8FAFC
}

' =========================
' ACTIVITY DIAGRAM
' =========================
skinparam activity {
    BackgroundColor #FFFFFF
    BorderColor MAIN
    DiamondBackgroundColor LIGHT
    DiamondBorderColor MAIN
}

' =========================
' USECASE
' =========================
skinparam usecase {
    BackgroundColor #FFFFFF
    BorderColor MAIN
}

' =========================
' LEGEND
' =========================
skinparam legend {
    BackgroundColor #FFFFFF
    BorderColor GRAY
}