@startuml

!include theme.puml

' Layout plus propre
top to bottom direction
skinparam linetype ortho

[*] --> Welcome

Welcome --> Rules : règles
Rules --> Welcome :retour

Welcome --> LobbyList :entrer
LobbyList --> Welcome : \n\n   retour

LobbyList --> Lobby : créer / joindre
Lobby --> LobbyList : \n\n   quitter

Lobby --> Game : prêt
Game --> End : fin

End --> Lobby : retour

@enduml