@startuml

!include theme.puml

top to bottom direction

[*] --> Welcome

Welcome --> Rules : bouton règles
Welcome --> LobbyList : bouton entrer

Rules --> Welcome : bouton retour

LobbyList --> Welcome : bouton retour
LobbyList --> Lobby : bouton créer / joindre

Lobby --> LobbyList : bouton quitter
Lobby --> Game : bouton prêt et tous prêts

Game --> End : fin de partie

End --> Lobby : bouton retour au lobby

@enduml